-- phpMyAdmin SQL Dump
-- version 4.9.0.1
-- https://www.phpmyadmin.net/
--
-- Host: sql208.infinityfree.com
-- Generation Time: Oct 20, 2024 at 02:35 PM
-- Server version: 10.6.19-MariaDB
-- PHP Version: 7.2.22

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `if0_37517218_sneakerhub`
--

-- --------------------------------------------------------

--
-- Table structure for table `products`
--

CREATE TABLE `products` (
  `id` int(11) NOT NULL,
  `title` varchar(255) NOT NULL,
  `price` decimal(10,0) NOT NULL,
  `brandname` varchar(100) NOT NULL,
  `image` varchar(255) NOT NULL,
  `description` text NOT NULL,
  `Category` tinyint(4) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `products`
--

INSERT INTO `products` (`id`, `title`, `price`, `brandname`, `image`, `description`, `Category`) VALUES
(1, 'Red Golf Tee', '35', 'Non-Branded', '/website/images/pngwing.com1.png', 'A soft cotton tee with a compound of nylon to give you a strong and durable tee to last you ages.\r\nIt is machine washable and hand washable ', 1),
(2, 'Nike AirMax 90', '95', 'Nike', '/website/images/pngwing.com9.png', '<p>Experience the perfect blend of style and comfort with the Nike Air Max 90. Known for its timeless silhouette and responsive cushioning, this sneaker is a staple for any wardrobe.</p>\r\n    \r\n    <h4>Key Features:</h4>\r\n    <ul class=\"key-features\">\r\n        <li>Iconic design with retro appeal</li>\r\n        <li>Visible Air unit for superior cushioning</li>\r\n        <li>Durable leather and mesh construction</li>\r\n        <li>Variety of colorways to match your style</li>\r\n        <li>Rubber outsole for enhanced traction</li>\r\n    </ul>', 2),
(3, 'Vans SK8', '75', 'Vans', '/website/images/pngwing.com7.png', '<p>Step into classic style with the Vans Off The Wall Low Cut Shoes. These iconic sneakers are designed for comfort, durability, and a timeless look that fits any occasion.</p>\r\n    \r\n    <h4>Key Features:</h4>\r\n    <ul class=\"key-features\">\r\n        <li><strong>Classic Low-Top Design:</strong> The low-cut silhouette offers a versatile style that pairs well with jeans, shorts, or skirts, making it a staple in any wardrobe.</li>\r\n        <li><strong>Durable Canvas Upper:</strong> Made with high-quality canvas, these shoes are lightweight, breathable, and built to withstand everyday wear.</li>\r\n        <li><strong>Signature Rubber Outsole:</strong> The vulcanized rubber outsole provides excellent grip and traction, ensuring stability on various surfaces.</li>\r\n        <li><strong>Padded Collar:</strong> The padded collar enhances comfort and support, making these shoes perfect for all-day wear.</li>\r\n        <li><strong>Iconic Branding:</strong> Featuring the classic Vans logo, these shoes showcase your love for skate culture and street style.</li>\r\n    </ul>', 2),
(5, 'Nike AirMax 97', '130', 'Nike', '/website/images/pngwing.com8.png', 'Elevate your sneaker game with the iconic Nike Air Max 97. This shoe blends innovative technology with a sleek, stylish design, making it a must-have for both casual wear and athletic performance.\r\n\r\nKey Features:\r\n<ul>\r\n<li>Iconic Silhouette: The Air Max 97’s wave-like design is inspired by rippling water, offering a unique aesthetic that stands out in any crowd.</li>\r\n<li>Comfortable Cushioning: Equipped with a full-length visible Air unit, these sneakers provide superior cushioning and support for all-day comfort.</li>\r\n<li>Premium Materials: Crafted from a mix of durable leather, synthetic materials, and mesh, the Air Max 97 ensures breathability and durability.</li>\r\n<li>Versatile Style: Available in a variety of colorways, the Air Max 97 effortlessly complements any outfit, whether you’re dressing up or keeping it casual.</li>\r\n<li>Traction and Stability: The rubber outsole features a wavy design for enhanced traction, ensuring you stay grounded on any surface.</li>\r\n</ul>\r\n\r\nWhy You’ll Love Them:\r\nThe Nike Air Max 97 is not just a sneaker; it’s a statement. With its combination of retro and modern elements, it appeals to sneaker enthusiasts and newcomers alike. Perfect for running errands, hitting the gym, or just hanging out with friends, the Air Max 97 delivers functionality without sacrificing style.', 2),
(6, 'High Top Converse All Star', '75', 'Chuck Taylor Converse', '/website/images/pngwing.com13.png', '<p>Embrace timeless style with the Converse All Star High Cut Shoes. These classic sneakers are a staple in fashion and culture, known for their versatility and iconic design.</p>\r\n    \r\n    <h4>Key Features:</h4>\r\n    <ul class=\"key-features\">\r\n        <li><strong>Iconic High-Top Design:</strong> The high cut silhouette provides ankle support and a distinctive look that pairs seamlessly with any outfit.</li>\r\n        <li><strong>Durable Canvas Upper:</strong> Crafted from sturdy canvas, these shoes are lightweight and breathable, perfect for everyday wear.</li>\r\n        <li><strong>Signature Rubber Toe Cap:</strong> The signature rubber toe cap enhances durability while giving the shoe its classic appeal.</li>\r\n        <li><strong>Vulcanized Rubber Outsole:</strong> The vulcanized rubber outsole offers excellent traction and flexibility, making them suitable for various activities.</li>\r\n        <li><strong>Customizable Style:</strong> Available in a wide range of colors and patterns, these shoes allow you to express your individuality and style.</li>\r\n    </ul>', 2),
(7, 'Nike Jordan Air 4', '250', 'Nike', '/website/images/pngwing5.png', '<p>The Nike Air Jordan 4, a legendary sneaker in the Jordan lineup, combines performance and style for the ultimate basketball experience. With its iconic design and rich heritage, the Air Jordan 4 is a must-have for sneaker enthusiasts and athletes alike.</p>\r\n    \r\n    <h4>Key Features:</h4>\r\n    <ul class=\"key-features\">\r\n        <li><strong>Iconic Design:</strong> The unique silhouette features a mesh and leather upper, giving it a distinctive look that stands out on and off the court.</li>\r\n        <li><strong>Responsive Cushioning:</strong> Equipped with Air-Sole units, the Air Jordan 4 provides exceptional cushioning and comfort for all-day wear.</li>\r\n        <li><strong>Supportive Fit:</strong> The padded collar and tongue enhance support and comfort, ensuring a secure fit during play.</li>\r\n        <li><strong>Durable Traction:</strong> The rubber outsole features a herringbone pattern for superior grip and traction on various surfaces.</li>\r\n        <li><strong>Heritage Appeal:</strong> With a legacy rooted in basketball history, the Air Jordan 4 remains a cultural icon, embraced by fans across generations.</li>\r\n    </ul>', 2),
(8, 'Nike Air Jordan 1 Retro', '350', 'Nike', '/website/images/pngwing10.png', '<p>The Nike Air Jordan 1 Retro is a timeless classic that revolutionized basketball footwear. With its rich history and iconic design, this sneaker remains a favorite for both athletes and sneaker enthusiasts alike.</p>\r\n    \r\n    <h4>Key Features:</h4>\r\n    <ul class=\"key-features\">\r\n        <li><strong>Classic High-Top Design:</strong> The high-cut silhouette provides excellent ankle support while delivering a standout style.</li>\r\n        <li><strong>Premium Leather Upper:</strong> Crafted from high-quality leather, the upper ensures durability and a premium feel.</li>\r\n        <li><strong>Air-Sole Cushioning:</strong> The integrated Air-Sole unit offers responsive cushioning for superior comfort during wear.</li>\r\n        <li><strong>Rubber Outsole:</strong> The rubber outsole features a herringbone pattern for exceptional traction and grip on various surfaces.</li>\r\n        <li><strong>Heritage Style:</strong> With its iconic swoosh and Air Jordan branding, the Retro 1 is a symbol of basketball culture and sneaker history.</li>\r\n    </ul>', 2),
(9, 'Low top Converse All Star', '58', 'Converse All Star', '/website/images/pngwing.com16.png', '<p>The Converse Low Top Shoes are a staple in casual footwear, known for their timeless design and versatility. Perfect for everyday wear, these sneakers seamlessly blend comfort with style.</p>\r\n    \r\n    <h4>Key Features:</h4>\r\n    <ul class=\"key-features\">\r\n        <li><strong>Classic Low-Top Silhouette:</strong> The low-cut design provides a relaxed fit that pairs well with any outfit.</li>\r\n        <li><strong>Durable Canvas Upper:</strong> Made from high-quality canvas, these shoes are breathable and built to last.</li>\r\n        <li><strong>Signature Rubber Toe Cap:</strong> The signature rubber toe cap enhances durability while maintaining the shoe\'s iconic look.</li>\r\n        <li><strong>Vulcanized Rubber Outsole:</strong> The vulcanized rubber outsole offers superior traction and flexibility for all-day comfort.</li>\r\n        <li><strong>Customizable Style:</strong> Available in a variety of colors and patterns, these shoes allow you to express your personal style.</li>\r\n    </ul>', 2),
(10, 'Nike Air Zoom Structure 24', '85', 'Nike', '/website/images/pngwing.com6.png', '<p>The Nike Air Zoom Structure 24 is engineered for stability and comfort, making it the perfect running companion for both casual joggers and dedicated athletes. With its responsive cushioning and supportive design, this shoe is built to handle any distance.</p>\r\n    \r\n    <h4>Key Features:</h4>\r\n    <ul class=\"key-features\">\r\n        <li><strong>Responsive Zoom Air Cushioning:</strong> The Zoom Air units provide a springy feel, offering excellent energy return with every step.</li>\r\n        <li><strong>Dynamic Fit Technology:</strong> The shoe features a snug fit around the midfoot, ensuring stability and support during runs.</li>\r\n        <li><strong>Durable Upper:</strong> Made with breathable mesh and synthetic overlays, the upper promotes airflow while enhancing durability.</li>\r\n        <li><strong>Supportive Midsole:</strong> The foam midsole is designed for cushioning and support, perfect for overpronators.</li>\r\n        <li><strong>Rubber Outsole:</strong> The traction pattern on the rubber outsole provides grip on various surfaces, enhancing performance and control.</li>', 2),
(11, 'Adidas Barricade', '45', 'Adidas', '/website/images/pngwing.com14.png', '<p>The Adidas Barricade is designed for serious tennis players who demand performance, stability, and comfort on the court. Known for its durability and support, this shoe is built to withstand intense matches while providing optimal performance.</p>\r\n    \r\n    <h4>Key Features:</h4>\r\n    <ul class=\"key-features\">\r\n        <li><strong>Durable Upper:</strong> Constructed with a blend of synthetic materials, the upper offers breathability and support for long-lasting wear.</li>\r\n        <li><strong>Responsive Cushioning:</strong> The EVA midsole provides excellent shock absorption and comfort, helping you stay agile during play.</li>\r\n        <li><strong>Stability Features:</strong> The Torsion System enhances midfoot stability, allowing for quick lateral movements without compromising support.</li>\r\n        <li><strong>Adiwear Outsole:</strong> The high-abrasion rubber outsole delivers superior grip and durability, ideal for hard court surfaces.</li>\r\n        <li><strong>Classic Design:</strong> The sleek silhouette and iconic three stripes make the Barricade a stylish choice both on and off the court.</li>\r\n    </ul>', 2),
(12, 'Nike Air Pegasus 30', '55', 'Nike', '/website/images/pngwing.com4.png', '<p>The Nike Air Pegasus 30 is a versatile running shoe designed for comfort and performance. Perfect for both seasoned runners and casual athletes, this shoe combines lightweight construction with responsive cushioning to deliver a smooth ride on any surface.</p>\r\n    \r\n    <h4>Key Features:</h4>\r\n    <ul class=\"key-features\">\r\n        <li><strong>Lightweight Mesh Upper:</strong> The breathable mesh upper promotes airflow, keeping your feet cool and comfortable during runs.</li>\r\n        <li><strong>Responsive Cushioning:</strong> Nike\'s Air-Sole unit provides optimal cushioning and support, enhancing comfort with every step.</li>\r\n        <li><strong>Dynamic Fit Technology:</strong> The shoe wraps your foot for a secure fit, allowing for natural movement and stability.</li>\r\n        <li><strong>Durable Rubber Outsole:</strong> The rubber outsole features a traction pattern that improves grip on various surfaces, ensuring durability and performance.</li>\r\n        <li><strong>Classic Style:</strong> With its sleek design and iconic branding, the Pegasus 30 is as stylish as it is functional.</li>\r\n    </ul>', 2),
(13, 'Nike Air Max 100', '55', 'Nike', '/website/images/pngwing.com11.png', ' <p>The Nike Air Max 100 combines iconic style with advanced comfort technology, making it the perfect choice for both casual wear and athletic performance. With its striking design and cushioned support, this shoe is built to keep you comfortable and stylish all day long.</p>\r\n    \r\n    <h4>Key Features:</h4>\r\n    <ul class=\"key-features\">\r\n        <li><strong>Iconic Air Max Cushioning:</strong> The visible Air unit in the heel provides responsive cushioning, ensuring a comfortable stride with every step.</li>\r\n        <li><strong>Premium Upper Materials:</strong> Crafted from a combination of breathable mesh and durable synthetic overlays, the upper promotes airflow and support.</li>\r\n        <li><strong>Dynamic Fit:</strong> The shoe features a snug fit that adapts to your foot\'s shape, enhancing stability during movement.</li>\r\n        <li><strong>Durable Rubber Outsole:</strong> The rubber outsole offers excellent traction and durability, making it suitable for various surfaces.</li>\r\n        <li><strong>Stylish Design:</strong> With its sleek silhouette and bold color options, the Air Max 100 is a statement piece for any wardrobe.</li>\r\n    </ul>', 2),
(14, 'Nike ACG Lupineck Flyknit SFB', '500', 'Nike', '/website/images/pngwing.com12.png', '<p>The Nike ACG Lupineck Flyknit SFB is designed for the adventurous spirit, offering a perfect blend of style, comfort, and functionality. This shoe is built to handle rugged terrains while providing a lightweight fit, making it ideal for outdoor enthusiasts.</p>\r\n    \r\n    <h4>Key Features:</h4>\r\n    <ul class=\"key-features\">\r\n        <li><strong>Flyknit Upper:</strong> The flexible and breathable Flyknit material wraps your foot for a snug, sock-like fit and enhances mobility.</li>\r\n        <li><strong>Durable Construction:</strong> Reinforced areas provide added protection and support, ensuring longevity in harsh conditions.</li>\r\n        <li><strong>Comfortable Cushioning:</strong> The responsive midsole offers excellent cushioning, making each step comfortable, whether on trails or city streets.</li>\r\n        <li><strong>Multi-Directional Traction:</strong> The rugged outsole features a traction pattern designed for optimal grip on various surfaces, from rocky paths to wet ground.</li>\r\n        <li><strong>All-Conditions Gear (ACG):</strong> Designed for versatility, the ACG Lupineck is ready for any weather, keeping you prepared for your next adventure.</li>\r\n    </ul>', 2),
(15, 'Nike Air-Force 1 High Cut', '150', 'Nike', '/website/images/pngwing.com(13).png', '<p>The Nike Air Force 1 High Cut is a classic sneaker that blends heritage style with modern comfort. Originally designed for basketball, this iconic shoe has transcended the court to become a staple in streetwear and fashion around the world.</p>\r\n    \r\n    <h4>Key Features:</h4>\r\n    <ul class=\"key-features\">\r\n        <li><strong>High-Top Design:</strong> The high-cut silhouette provides excellent ankle support and a bold look that stands out.</li>\r\n        <li><strong>Premium Leather Upper:</strong> Crafted from high-quality leather, the upper ensures durability and a sleek finish.</li>\r\n        <li><strong>Air-Sole Cushioning:</strong> The encapsulated Air unit in the sole delivers lightweight cushioning for all-day comfort.</li>\r\n        <li><strong>Rubber Outsole:</strong> The classic rubber outsole features a pivot point design for enhanced traction and stability on various surfaces.</li>\r\n        <li><strong>Timeless Style:</strong> With its iconic design and Nike branding, the Air Force 1 High Cut remains a fashionable choice for any outfit.</li>\r\n    </ul>', 2),
(16, 'New Balance 574', '58', 'New Balance', '/website/images/pngwing.com(10).png', '<p>The New Balance 574 is a classic sneaker that combines retro style with modern comfort. Known for its versatility and support, this shoe is perfect for both casual outings and athletic pursuits, making it a staple in any wardrobe.</p>\r\n    \r\n    <h4>Key Features:</h4>\r\n    <ul class=\"key-features\">\r\n        <li><strong>Iconic Design:</strong> The 574 features a timeless silhouette that effortlessly blends with a variety of outfits.</li>\r\n        <li><strong>Breathable Upper:</strong> Crafted from a mix of suede and mesh, the upper ensures breathability and durability for everyday wear.</li>\r\n        <li><strong>Cushioned Midsole:</strong> The EVA foam midsole provides lightweight cushioning, enhancing comfort and support during activities.</li>\r\n        <li><strong>Durable Outsole:</strong> The rubber outsole offers excellent traction and durability, suitable for various surfaces.</li>\r\n        <li><strong>Classic Branding:</strong> Featuring the iconic \"N\" logo, the New Balance 574 is recognized for its quality and style.</li>\r\n    </ul>', 2),
(17, 'Nike Dunk Low', '300', 'Nike', '/website/images/pngwing(7).png', '<p>The Nike Dunk Low is a timeless sneaker that seamlessly blends street style with athletic performance. Originally designed for basketball, this shoe has become a favorite in sneaker culture, making it a versatile option for any wardrobe.</p>\r\n    \r\n    <h4>Key Features:</h4>\r\n    <ul class=\"key-features\">\r\n        <li><strong>Classic Low-Top Design:</strong> The low-cut silhouette offers a sleek look that pairs well with any outfit.</li>\r\n        <li><strong>Durable Upper:</strong> Made from premium leather and synthetic materials, the upper ensures lasting durability and support.</li>\r\n        <li><strong>Cushioned Comfort:</strong> The padded collar and tongue provide additional comfort, making these shoes suitable for all-day wear.</li>\r\n        <li><strong>Rubber Outsole:</strong> The rubber outsole features a pivot point design for superior traction and grip on various surfaces.</li>\r\n        <li><strong>Iconic Branding:</strong> With its recognizable Swoosh logo and bold colorways, the Dunk Low stands out as a fashion statement.</li>\r\n    </ul>', 2),
(18, 'Nike Air-Force 1 Low Cut', '120', 'Nike', '/website/images/pngwing.com(2).png', ' <p>The Nike Air Force 1 Low Cut is a legendary sneaker that combines classic style with modern comfort. Originally launched in 1982, this iconic shoe has transcended its basketball roots to become a staple in streetwear and casual fashion.</p>\r\n    \r\n    <h4>Key Features:</h4>\r\n    <ul class=\"key-features\">\r\n        <li><strong>Timeless Low-Top Design:</strong> The low-cut silhouette offers a sleek and versatile look that pairs well with any outfit.</li>\r\n        <li><strong>Premium Leather Upper:</strong> Crafted from high-quality leather, the upper provides durability and a polished appearance.</li>\r\n        <li><strong>Air-Sole Cushioning:</strong> The encapsulated Air unit in the heel delivers lightweight cushioning for all-day comfort.</li>\r\n        <li><strong>Rubber Outsole:</strong> The classic rubber outsole features a pivot point design for enhanced traction and durability on various surfaces.</li>\r\n        <li><strong>Iconic Branding:</strong> With its signature Swoosh logo and AF1 branding, this sneaker is recognized worldwide as a symbol of style.</li>\r\n    </ul>', 2),
(19, 'Adidas Gazelle Trainers Limited Edition', '140', 'Adidas', '/website/images/pngwing(14).png', '<p>The Adidas Gazelle Trainers Limited Edition is a celebration of classic style and modern comfort. Originally launched in the 1960s, the Gazelle has become an iconic sneaker, beloved for its simplicity and versatility. This limited edition release features unique design elements that make it a must-have for collectors and fashion enthusiasts alike.</p>\r\n    \r\n    <h4>Key Features:</h4>\r\n    <ul class=\"key-features\">\r\n        <li><strong>Premium Suede Upper:</strong> Crafted from high-quality suede, the upper provides a soft touch and luxurious feel.</li>\r\n        <li><strong>Classic Gazelle Design:</strong> The timeless silhouette features signature three stripes and a clean profile, making it a versatile choice for any outfit.</li>\r\n        <li><strong>Cushioned Midsole:</strong> The lightweight EVA midsole offers excellent cushioning for all-day comfort and support.</li>\r\n        <li><strong>Rubber Outsole:</strong> The durable rubber outsole features a classic tread pattern for reliable traction on various surfaces.</li>\r\n        <li><strong>Limited Edition Details:</strong> Unique branding and colorways make this version of the Gazelle a standout choice for sneaker enthusiasts.</li>\r\n    </ul>', 2),
(20, 'Adidas Superstar ', '70', 'Adidas', '/website/images/pngwing.com(3).png', '<p>The Adidas Superstar is a timeless sneaker that has made its mark in both sports and fashion. Originally designed as a basketball shoe in the 1970s, the Superstar has evolved into a cultural icon, known for its distinctive design and versatility.</p>\r\n    \r\n    <h4>Key Features:</h4>\r\n    <ul class=\"key-features\">\r\n        <li><strong>Classic Shell Toe:</strong> The signature rubber shell toe not only adds durability but also provides a unique aesthetic that sets the Superstar apart.</li>\r\n        <li><strong>Premium Leather Upper:</strong> Crafted from high-quality leather, the upper offers a sleek look and ensures lasting comfort.</li>\r\n        <li><strong>Comfortable Fit:</strong> The padded collar and tongue enhance comfort, making these shoes suitable for all-day wear.</li>\r\n        <li><strong>Durable Rubber Outsole:</strong> The rubber outsole features a herringbone tread pattern for excellent traction and stability on various surfaces.</li>\r\n        <li><strong>Iconic Branding:</strong> With the classic three stripes and Adidas logo, the Superstar remains a symbol of style and authenticity.</li>\r\n    </ul>', 2),
(22, 'Nike Kyrie 2', '450', 'Nike', '/website/images/pngwing.com(5).png', '<p>The Nike Kyrie 2 is designed for the dynamic player who values agility and responsiveness on the court. Inspired by Kyrie Irving\'s unique style of play, this shoe combines cutting-edge technology with a sleek design, making it a favorite among basketball enthusiasts.</p>\r\n    \r\n    <h4>Key Features:</h4>\r\n    <ul class=\"key-features\">\r\n        <li><strong>Dynamic Fit Collar:</strong> The high-top design provides excellent ankle support and a secure fit, allowing for quick lateral movements.</li>\r\n        <li><strong>Zoom Air Cushioning:</strong> The forefoot Zoom Air unit delivers responsive cushioning, ensuring comfort during fast-paced play.</li>\r\n        <li><strong>Durable Upper:</strong> Constructed with a combination of materials, the upper offers breathability and support for long-lasting wear.</li>\r\n        <li><strong>Traction Pattern:</strong> The outsole features a multi-directional traction pattern, providing exceptional grip and control on the court.</li>\r\n        <li><strong>Signature Style:</strong> With its bold design and unique colorways, the Kyrie 2 showcases a blend of performance and style that stands out on and off the court.</li>\r\n    </ul>', 2),
(23, 'Nike Air Huarache Run Ultra', '250', 'Nike', '/website/images/pngwing(6).png', ' <p>The Nike Air Huarache Run Ultra is a modern take on the classic Huarache silhouette, blending style and performance for everyday wear. Known for its unique design and exceptional comfort, this shoe is perfect for those who appreciate both fashion and function.</p>\r\n    \r\n    <h4>Key Features:</h4>\r\n    <ul class=\"key-features\">\r\n        <li><strong>Ultra-Lightweight Construction:</strong> The lightweight materials ensure a comfortable fit, making it ideal for all-day wear.</li>\r\n        <li><strong>Breathable Mesh Upper:</strong> The mesh upper enhances airflow, keeping your feet cool and comfortable during activities.</li>\r\n        <li><strong>Phylon Midsole:</strong> The cushioned Phylon midsole provides lightweight support and responsiveness for a smooth ride.</li>\r\n        <li><strong>Rubber Outsole:</strong> The rubber outsole features a durable tread pattern for excellent traction on various surfaces.</li>\r\n        <li><strong>Iconic Design:</strong> With its distinctive heel counter and bold colorways, the Huarache Run Ultra stands out as a style statement.</li>\r\n    </ul>', 2),
(24, 'Nike Air Jordan XI Retro Low', '500', 'Nike', '/website/images/pngwing(8).png', ' <p>The Nike Air Jordan XI Retro Low is a timeless sneaker that pays homage to one of the most iconic silhouettes in basketball history. Combining luxury materials with a sleek design, this shoe is perfect for both on and off the court, making it a must-have for sneaker enthusiasts and casual wearers alike.</p>\r\n    \r\n    <h4>Key Features:</h4>\r\n    <ul class=\"key-features\">\r\n        <li><strong>Premium Upper:</strong> Crafted from a mix of patent leather and mesh, the upper provides a stylish look and breathable comfort.</li>\r\n        <li><strong>Responsive Cushioning:</strong> The Air-Sole unit in the heel delivers lightweight cushioning, ensuring comfort during wear.</li>\r\n        <li><strong>Translucent Rubber Outsole:</strong> The rubber outsole features a herringbone traction pattern for excellent grip on various surfaces.</li>\r\n        <li><strong>Signature Branding:</strong> The iconic Jumpman logo and \"23\" detailing showcase the shoe\'s heritage and connection to Michael Jordan.</li>\r\n        <li><strong>Classic Design:</strong> With its low-cut silhouette and elegant colorways, the Air Jordan XI Retro Low easily transitions from court to street.</li>\r\n    </ul>', 2),
(25, '361 Low Tops', '45', '361', '/website/images/pngwing(9).png', ' <p>The 361 Low Top Shoe is designed for those who seek comfort and style in a versatile sneaker. Combining modern aesthetics with performance-driven features, this shoe is perfect for everyday wear, whether you\'re hitting the gym or exploring the city.</p>\r\n    \r\n    <h4>Key Features:</h4>\r\n    <ul class=\"key-features\">\r\n        <li><strong>Breathable Upper:</strong> Made with lightweight, breathable materials that enhance airflow and keep your feet cool.</li>\r\n        <li><strong>Cushioned Midsole:</strong> The responsive midsole provides optimal cushioning, ensuring comfort during all-day wear.</li>\r\n        <li><strong>Durable Outsole:</strong> The rubber outsole offers reliable traction and durability on various surfaces, making it suitable for multiple activities.</li>\r\n        <li><strong>Stylish Design:</strong> With a sleek silhouette and modern color options, the 361 Low Top Shoe complements any outfit.</li>\r\n        <li><strong>Comfort Fit:</strong> The low-top design allows for easy movement and a snug fit, perfect for active lifestyles.</li>\r\n    </ul>', 2),
(26, 'Nike KD9', '155', 'Nike', '/website/images/pngwing.com(11).png', '<p>The Nike KD9 is a performance basketball shoe designed for Kevin Durant’s dynamic playing style. Featuring innovative technology and a sleek design, the KD9 provides exceptional support, responsiveness, and comfort on the court, making it a favorite among serious athletes.</p>\r\n    \r\n    <h4>Key Features:</h4>\r\n    <ul class=\"key-features\">\r\n        <li><strong>Flyknit Upper:</strong> The lightweight and breathable Flyknit construction wraps your foot for a snug, adaptive fit.</li>\r\n        <li><strong>Zoom Air Cushioning:</strong> The full-length Zoom Air unit delivers responsive cushioning, ensuring comfort during explosive movements.</li>\r\n        <li><strong>Seamless Design:</strong> The seamless construction minimizes irritation, allowing for a distraction-free fit and feel.</li>\r\n        <li><strong>Durable Rubber Outsole:</strong> The herringbone traction pattern on the outsole provides excellent grip and stability on the court.</li>\r\n        <li><strong>Signature Style:</strong> With its bold design and unique colorways, the KD9 reflects Kevin Durant’s personal style and on-court prowess.</li>\r\n    </ul>', 2),
(27, 'Adidas Pureboost', '89', 'Adidas', '/website/images/pngwing(12).png', '<p>The Adidas Pureboost is designed for runners who seek a natural feel and exceptional energy return with every step. Combining innovative technologies with a sleek design, this shoe is perfect for both casual jogs and high-performance runs.</p>\r\n    \r\n    <h4>Key Features:</h4>\r\n    <ul class=\"key-features\">\r\n        <li><strong>Boost Midsole:</strong> The revolutionary Boost technology offers outstanding energy return and cushioning, providing a responsive ride.</li>\r\n        <li><strong>Primeknit Upper:</strong> The adaptable Primeknit upper wraps the foot for a snug yet breathable fit, enhancing comfort and support.</li>\r\n        <li><strong>Fitcounter Heel:</strong> The heel design allows for natural movement of the Achilles tendon, promoting a comfortable fit.</li>\r\n        <li><strong>Continental Rubber Outsole:</strong> The durable outsole provides excellent traction on various surfaces, ensuring stability and grip.</li>\r\n        <li><strong>Sleek Aesthetic:</strong> With its minimalist design and modern colorways, the Pureboost seamlessly transitions from the track to everyday wear.</li>\r\n    </ul>', 2),
(28, 'Puma Speed Cat', '77', 'Puma', '/website/images/pngwing.com(15).png', 'p>The Puma Speed Cat is a stylish and versatile sneaker inspired by motorsport culture. Known for its sleek design and comfort, this shoe is perfect for both casual outings and high-speed activities, making it a favorite among automotive enthusiasts and fashion-forward individuals alike.</p>\r\n    \r\n    <h4>Key Features:</h4>\r\n    <ul class=\"key-features\">\r\n        <li><strong>Premium Leather Upper:</strong> Crafted from high-quality leather, the upper offers durability and a sophisticated look.</li>\r\n        <li><strong>Lightweight Construction:</strong> The shoe’s lightweight design ensures comfort and ease of movement, ideal for everyday wear.</li>\r\n        <li><strong>Low-Profile Silhouette:</strong> The low-cut design enhances ankle mobility while providing a sleek and streamlined appearance.</li>\r\n        <li><strong>Rubber Outsole:</strong> The rubber outsole provides excellent grip and traction, making it suitable for various surfaces.</li>\r\n        <li><strong>Iconic Branding:</strong> Featuring the classic Puma logo and motorsport-inspired detailing, the Speed Cat represents a blend of style and performance.</li>\r\n    </ul>', 2),
(29, 'Adidas Bercuda', '74', 'Adidas', '/website/images/pngwing.com(16).png', '<p>The Puma Speed Cat is a modern classic that fuses motorsport-inspired design with everyday comfort. Known for its sleek lines and stylish appearance, this sneaker is perfect for those who appreciate performance and fashion in one package.</p>\r\n    \r\n    <h4>Key Features:</h4>\r\n    <ul class=\"key-features\">\r\n        <li><strong>Premium Leather Upper:</strong> Made from high-quality leather, the upper provides durability and a refined look.</li>\r\n        <li><strong>Lightweight and Comfortable:</strong> The lightweight construction ensures ease of movement, making it ideal for daily wear.</li>\r\n        <li><strong>Low-Profile Design:</strong> The low-cut silhouette enhances ankle mobility while delivering a sleek aesthetic.</li>\r\n        <li><strong>Rubber Outsole:</strong> The rubber outsole offers excellent traction and grip, suitable for various surfaces.</li>\r\n        <li><strong>Iconic Branding:</strong> Featuring the classic Puma logo and motorsport accents, the Speed Cat is a statement of style and performance.</li>\r\n    </ul>', 2);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `products`
--
ALTER TABLE `products`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `products`
--
ALTER TABLE `products`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=30;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
